export enum TicketStatus {
  AVAILABLE = "AVAILABLE",
  SOLD = "SOLD",
  RESERVED = "RESERVED",
  CANCELED = "CANCELED",
  EXPIRED = "EXPIRED",
  PENDING = "PENDING",
  REFUNDED = "REFUNDED",
  TRANSFERRED = "TRANSFERRED",
}
